config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #this can replace all the routes we manually defined
  resources :blog_posts
  
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update" # you don't need a name here - it will look at the show route url - it doesn't care about the request type
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit/", to: "blog_posts#edit", as: :edit_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  # This goes in a separate database table and it sets up association between the two tables
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

# second argument is secondary sorting
  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc)}
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end

  def format_date
    published_at? ? published_at.strftime('%m.%d.%Y') : ''
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # this helper method can replace the .find()
  before_action :set_blog_post, except: [:index, :new, :create] # only: [:show, :edit, :update, :destroy]

  def index
    # look up all posts and save to an instance variable
    # rails knows to share these with the erb templates
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end

  def show
  end

  def new
    # creates a blog_post in memory, but not the database
    @blog_post = BlogPost.new
  end

  def create
    # rails does not allow you to pass params directly to the model for security reasons
    # @blog_post = BlogPost.new(params[:blog_post])
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      # status gives us the correct response code in our http request
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # this is a helper method that equates to "/"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<div class="mt-12">
  <%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
      <div>
        <% form.object.errors.full_messages.each do |message| %>
          <div class="text-pink-700 font-bold mb-2"><span>**</span><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div class="flex flex-col gap-6">
      <div>
        <div class="form-label">
          <%= form.label :title %>
        </div>
        <%= form.text_field :title, size: 50 %>
      </div>

      <div>
        <div class="form-label">
          <%= form.label :content %>
        </div>
        <%= form.rich_text_area :content %>
      </div>

      <div>
        <div class="form-label">
          <%= form.label :published_at %>
        </div>
        <%= form.datetime_select :published_at, include_blank: true %>
      </div>
    </div>

    <div class="form-button bg-yellow-200 mt-8">
      <%= form.button %>
    </div>
  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}, class:"form-button mt-3 mb-8 bg-pink-600"  %>

app/views/blog_posts/index.html.erb
<div class="flex justify-center">
  <div class="max-w-3xl">
    <% @blog_posts.each do |blog_post| %>
      <div class="mt-6 lg:mt-12 border-t-2 border-black ">
        <%# you can pass the active record as the path %>
        <% if blog_post.draft? %>
          <p class="published-label bg-yellow-500 text-white">draft</p>
        <% elsif blog_post.scheduled? %>
          <p class="published-label bg-pink-600 text-white">scheduled</p>
        <% end %>
        <div class="inline">
          <%= blog_post.format_date %>
        </div>
        <%= link_to blog_post.title, blog_post, class: "font-bold no-underline text-4xl hover:underline block pt-2" %>

        <div class="h-24 overflow-hidden mt-6"><%= blog_post.content %></div>

        <%= link_to "READ FULL POST...", blog_post, class: "no-underline italic inline-block mt-2 hover:bg-pink-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/blog_posts/new.html.erb
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<div class="flex lg:justify-end lg:px-4">
  <div class="bg-pink-200 px-6 mb-1 font-bold hover:bg-pink-600">
    <%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
  </div>
</div>

<div class="flex flex-col gap-4 lg:flex-row">
  <h1 class="basis-1/2 lg:pr-6 lg:text-right leading-tight lg:mt-6 font-bold text-4xl lg:text-[4.6vw]"><%= @blog_post.title %></h1>
  <div class="lg:p-4 basis-1/2 lg:border-l-2 lg:border-black"><%= @blog_post.content %></div>
</div>

app/views/home/_footer.html.erb
<footer class="mt-24 mb-4">
  <ul class="flex gap-4">
    <% if !user_signed_in? %>
      <li class="bg-pink-100 px-2 hover:underline hover:bg-pink-600"><%= link_to "ADMIN LOGIN", new_user_session_path %></li>
    <% end %>
      <li>
      <p class="">&#169; Copyright Megan Ratto 2023</p> 
      </li>
  </ul>
</footer>

app/views/home/_header.html.erb
<nav class="flex gap-3 mb-12">
  <%= link_to "LOREM IPSUM", root_path, class: "bg-pink-600 p-2 text-3xl sm:text-6xl font-bold no-underline inline-block" %>
  <ul class="flex flex-col mt-3">
    <% if user_signed_in? %>
      <li><%= button_to "LOG OUT", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <li class="nav-link"><%= link_to "NEW POST", new_blog_post_path, class: "no-underline" %></li>
      <%# <li><%= link_to "Profile", edit_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learn Rails Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="text-gray-900 flex flex-col min-h-screen justify-between bg-zinc-50">
    <div class="mx-auto w-full px-4 md:px-12 max-w-7xl">
      <%= render "home/header" %>
      <p class="notice text-pink-600 opacity-0 animate-fade-out"><%= notice %></p>
      <p class="alert text-pink-600 opacity-0 animate-fade-out"><%= alert %></p>

      <%= yield %>
    </div>
    <div class="mx-auto w-full px-4 md:px-12 max-w-7xl">
      <%= render "home/footer"%>
    </div>
  </body>
</html>